import { Users } from './users';

export const USERS: Users[] = [
    {   id: 1,
        firstName: 'Tony',
        lastName: 'Stark',
        username: 'ironman',
        password: 'avenger',
    },
    {   id: 2,
        firstName: 'Steve',
        lastName: 'Rogers',
        username: 'captainamerica',
        password: 'avenger',
    },
    {   id: 3,
        firstName: 'Bruce',
        lastName: 'Banner',
        username: 'hulk',
        password: 'avenger',
    },
    {   id: 4,
        firstName: 'Thor',
        lastName: 'Odinson',
        username: 'thor',
        password: 'avenger',
    },
    {   id: 5,
        firstName: 'Natasha',
        lastName: 'Romanoff',
        username: 'blackwidow',
        password: 'avenger',
    },
    {   id: 6,
        firstName: 'Clint',
        lastName: 'Barton',
        username: 'hawkeye',
        password: 'avenger',
    }
];

